/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.swing.todo.project.frame;

import com.swing.todo.project.entity.Tarea;
import com.swing.todo.project.entity.Usuario;
import com.swing.todo.project.repository.TareaRepository;
import com.swing.todo.project.repository.TareaRepositoryTxt;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LUIS
 */
public class HomeFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(HomeFrame.class.getName());

    private Usuario usuarioActual;
    private TareaRepository tareaRepository = new TareaRepositoryTxt();
    
    private List<Tarea> listaPendientes = new ArrayList<>();
    private List<Tarea> listaCompletadas = new ArrayList<>();
    
    public HomeFrame(Usuario usuario) {
        initComponents();
        this.usuarioActual = usuario;

        // Carga las tablas apenas se abre la ventana
        cargarTablasTareas();
    }

    private void cargarTablasTareas() {
        DefaultTableModel modelPendientes = (DefaultTableModel) pendientesTable.getModel();
        DefaultTableModel modelCompletadas = (DefaultTableModel) completadosTable.getModel();

        // 1. Limpiar filas de los modelos visuales
        modelPendientes.setRowCount(0);
        modelCompletadas.setRowCount(0);

        // 2. Limpiar listas auxiliares
        listaPendientes.clear();
        listaCompletadas.clear();

        // 3. Obtener todas las tareas del usuario desde el repositorio
        List<Tarea> todasLasTareas = tareaRepository.listarPorPersona(usuarioActual.getId());

        // 4. Clasificar cada tarea
        for (Tarea t : todasLasTareas) {
            Object[] fila = new Object[]{ t.getTarea(), t.getPrioridad() };

            if (t.isCompletada()) {
                listaCompletadas.add(t); // Sincroniza índice con tblCompletadas
                modelCompletadas.addRow(fila);
            } else {
                listaPendientes.add(t);  // Sincroniza índice con tblPendientes
                modelPendientes.addRow(fila);
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        addTaskButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pendientesTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        completadosTable = new javax.swing.JTable();
        editTaskButton = new javax.swing.JButton();
        detailTaskButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 1, 48)); // NOI18N
        jLabel1.setText("TO DO LIST - APLICACIÓN");

        addTaskButton.setText("+ Nueva Tarea");

        jLabel2.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        jLabel2.setText("Tareas pendientes");

        pendientesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tarea", "Prioridad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(pendientesTable);

        jLabel3.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        jLabel3.setText("Tareas completadas");

        completadosTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tarea", "Prioridad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(completadosTable);

        editTaskButton.setText("Editar Tarea");
        editTaskButton.addActionListener(this::editTaskButtonActionPerformed);

        detailTaskButton.setText("Ver Detalle");
        detailTaskButton.addActionListener(this::detailTaskButtonActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(detailTaskButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(editTaskButton)
                        .addGap(73, 73, 73)
                        .addComponent(addTaskButton))
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 678, Short.MAX_VALUE))
                .addGap(57, 57, 57))
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addTaskButton)
                    .addComponent(jLabel2)
                    .addComponent(editTaskButton))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(detailTaskButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void detailTaskButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailTaskButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_detailTaskButtonActionPerformed

    private void editTaskButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editTaskButtonActionPerformed
        // 1. Obtener la fila seleccionada en la tabla (-1 indica que no hay selección)
        int filaSeleccionada = pendientesTable.getSelectedRow();

            if (filaSeleccionada != -1) {
            // Obtener exactamente la Tarea seleccionada por su índice de fila
            Tarea tareaSeleccionada = listaPendientes.get(filaSeleccionada);

            // Abrir el Dialog pasando la tarea elegida y el repositorio
            TareaDetalleDialog dialog = new TareaDetalleDialog(this, true, tareaSeleccionada, tareaRepository);
            dialog.setVisible(true);

            // Al cerrar el Dialog, refrescar las tablas para actualizar cambios
            cargarTablasTareas();
        } else {
            javax.swing.JOptionPane.showMessageDialog(
                this, 
                "Seleccione una tarea pendiente de la tabla.", 
                "Atención", 
                javax.swing.JOptionPane.WARNING_MESSAGE
            );
        }
    }//GEN-LAST:event_editTaskButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addTaskButton;
    private javax.swing.JTable completadosTable;
    private javax.swing.JButton detailTaskButton;
    private javax.swing.JButton editTaskButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable pendientesTable;
    // End of variables declaration//GEN-END:variables
}
